datasources:
  default:
    connection:
      url: ${MONGO_URL}
    objectFiles:
      - "./src/**"
public:
  cfs:
    store: ${STEEDOS_CFS_STORE}
tenant:
  _id: ${STEEDOS_TENANT_ID}
  name: 华炎魔方
  logo_url:
  background_url:
  enable_register: true
  enable_forget_password: false
  enable_create_tenant: true
  enable_password_login: true
  enable_bind_email: false
  enable_bind_mobile: false
plugins:
  - "@steedos/accounts"
# cron:
  # instancerecordqueue_interval: 10000
  # push_interval: 1000
  # webhookqueue_interval: 1000